export const products = [
    {
        "idx": 123,
        "marca": "Villa del sur",
        "tamanio": "500 cc",
        "tipo": "Agua mineral",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/villa-del-sur-botella.png",
        "descripcion": "Villa del Sur presenta su agua mineral en un práctico formato de botella de 500 cc, perfecta para el consumo diario. Esta marca destaca por ofrecer agua purificada proveniente de fuentes naturales, garantizando frescura y pureza en cada sorbo.",
        "precio": 200,
        "stock": 19
    },
    {
        "idx": 234,
        "marca": "Bonaqua",
        "tamanio": "500 cc",
        "tipo": "Agua mineral",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/bonaqua-botella.png",
        "descripcion": "Bonaqua, reconocida en el mercado, presenta su agua mineral en botellas de 500 cc. Esta opción refrescante es ideal para la hidratación diaria, siendo una elección popular entre aquellos que buscan una bebida de alta calidad.",
        "precio": 150,
       "stock": 19
    },
    {
        "idx": 345,
        "marca": "Villavicencio",
        "tamanio": "500 cc",
        "tipo": "Agua mineral",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/villavicencio-botella.png",
        "descripcion": "Villavicencio, con su agua mineral en botellas de 500 cc, se distingue por ofrecer una opción refrescante y saludable. Proveniente de fuentes naturales, esta marca argentina asegura la pureza de su agua, brindando una experiencia refrescante única.",
        "precio": 220,
       "stock": 19
    },
    {
        "idx": 456,
        "marca": "Glaciar",
        "tamanio": "500 cc",
        "tipo": "Agua mineral",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/glaciar-botella.png",
        "descripcion": "Glaciar, en su presentación de agua mineral embotellada de 500 cc, se posiciona como una elección refrescante y práctica. Su origen en áreas con glaciares sugiere una fuente natural y pura para aquellos que buscan una opción de alta calidad.",
        "precio": 170,
       "stock": 19
    },
    {
        "idx": 789,
        "marca": "Heineken",
        "tamanio": "500 cc",
        "tipo": "Cerveza",
        "formato": "Lata",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/heineken-lata.png",
        "descripcion": "Heineken, reconocida mundialmente por su cerveza, ofrece sus refrescantes variedades en latas de 500 cc. Con un sabor distintivo, Heineken es la elección ideal para aquellos que aprecian una cerveza de calidad en envases prácticos.",
        "precio": 600,
       "stock": 19
    },
    {
        "idx": 321,
        "marca": "Heineken",
        "tamanio": "1 litro",
        "tipo": "Cerveza",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/heineken-botella.png",
        "descripcion": "Heineken, reconocida mundialmente por su cerveza, ofrece su refrescante sabor en esta botella de 1L. Con un sabor distintivo, Heineken es la elección ideal para aquellos que aprecian una cerveza de calidad en envases prácticos.",
        "precio": 1200,
       "stock": 19
    },
    {
        "idx": 432,
        "marca": "Stella Artois",
        "tamanio": "500 cc",
        "tipo": "Cerveza",
        "formato": "Lata",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/stella-artois-lata.png",
        "descripcion": "Stella Artois, tanto en lata de 500 cc como en botella de 1 litro, presenta opciones versátiles para los amantes de la cerveza. Esta marca ofrece una experiencia única con su selección de cervezas, adaptándose a diferentes preferencias de consumo.",
        "precio": 600,
       "stock": 19
    },
    {
        "idx": 543,
        "marca": "Stella Artois",
        "tamanio": "1 litro",
        "tipo": "Cerveza",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/stella-artois-botella.png",
        "descripcion": "Stella Artois, tanto en lata de 500 cc como en botella de 1 litro, presenta opciones versátiles para los amantes de la cerveza. Esta marca ofrece una experiencia única con su selección de cervezas, adaptándose a diferentes preferencias de consumo.",
        "precio": 1200,
       "stock": 19
    },
    {
        "idx": 654,
        "marca": "Quilmes",
        "tamanio": "500 cc",
        "tipo": "Cerveza",
        "formato": "Lata",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/quilmes-lata.png",
        "descripcion": "Quilmes, conocida por su tradición cervecera, presenta sus opciones en lata de 500 cc y botella de 1 litro. Esta cerveza argentina se destaca por su sabor auténtico, siendo una elección clásica para disfrutar en diferentes ocasiones.",
        "precio": 550,
       "stock": 19
    },
    {
        "idx": 765,
        "marca": "Quilmes",
        "tamanio": "1 litro",
        "tipo": "Cerveza",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/quilmes-botella.png",
        "descripcion": "Quilmes, conocida por su tradición cervecera, presenta sus opciones en lata de 500 cc y botella de 1 litro. Esta cerveza argentina se destaca por su sabor auténtico, siendo una elección clásica para disfrutar en diferentes ocasiones.",
        "precio": 1000,
       "stock": 19
    },
    {
        "idx": 987,
        "marca": "Brahma",
        "tamanio": "500 cc",
        "tipo": "Cerveza",
        "formato": "Lata",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/brahma-lata.png",
        "descripcion": "Brahma, en sus presentaciones de cerveza en lata de 500 cc y botella de 1 litro, ofrece opciones refrescantes para los amantes de esta bebida. Esta marca se caracteriza por su calidad y sabor distintivo.",
        "precio": 450,
       "stock": 19
    },
    {
        "idx": 111,
        "marca": "Brahma",
        "tamanio": "1 litro",
        "tipo": "Cerveza",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/brahma-botella.png",
        "descripcion": "Brahma, en sus presentaciones de cerveza en lata de 500 cc y botella de 1 litro, ofrece opciones refrescantes para los amantes de esta bebida. Esta marca se caracteriza por su calidad y sabor distintivo.",
        "precio": 800,
       "stock": 19
    },
    {
        "idx": 222,
        "marca": "Coca Cola",
        "tamanio": "330 cc",
        "tipo": "Gaseosa",
        "formato": "Lata",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/coca-cola-original-lata.png",
        "descripcion": "Coca Cola, en latas de 330 cc y botellas de 1.5 litros, presenta sus opciones de gaseosas clásicas. Reconocida a nivel mundial, Coca Cola ofrece una experiencia refrescante con su icónico sabor.",
        "precio": 350,
       "stock": 19
    },
    {
        "idx": 333,
        "marca": "Coca Cola",
        "tamanio": "1.5 litros",
        "tipo": "Gaseosa",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/coca-cola-original-botella.png",
        "descripcion": "Coca Cola, en latas de 330 cc y botellas de 1.5 litros, presenta sus opciones de gaseosas clásicas. Reconocida a nivel mundial, Coca Cola ofrece una experiencia refrescante con su icónico sabor.",
        "precio": 800,
       "stock": 19
    },
    {
        "idx": 444,
        "marca": "Sprite",
        "tamanio": "330 cc",
        "tipo": "Gaseosa",
        "formato": "Lata",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/sprite-lata.png",
        "descripcion": "Sprite, en latas de 330 cc y botellas de 1.5 litros, brinda opciones de gaseosa con un toque cítrico. Refrescante y ligera, Sprite es la elección ideal para quienes buscan una alternativa refrescante y sin cafeína.",
        "precio": 300,
       "stock": 19
    },
    {
        "idx": 555,
        "marca": "Sprite",
        "tamanio": "1.5 litros",
        "tipo": "Gaseosa",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/sprite-botella.png",
        "descripcion": "Sprite, en latas de 330 cc y botellas de 1.5 litros, brinda opciones de gaseosa con un toque cítrico. Refrescante y ligera, Sprite es la elección ideal para quienes buscan una alternativa refrescante y sin cafeína.",
        "precio": 700,
       "stock": 19
    },
    {
        "idx": 666,
        "marca": "Paso de los toros Pomelo",
        "tamanio": "330 cc",
        "tipo": "Gaseosa",
        "formato": "Lata",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/paso-de-los-toros-lata.png",
        "descripcion": "Paso de los Toros Pomelo, en latas de 330 cc y botellas de 1.5 litros, presenta sus gaseosas con sabor a pomelo. Esta opción única ofrece una experiencia refrescante y distintiva para aquellos que buscan nuevos sabores.",
        "precio": 300,
       "stock": 19
    },
    {
        "idx": 777,
        "marca": "Paso de los toros Pomelo",
        "tamanio": "1.5 litros",
        "tipo": "Gaseosa",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/paso-de-los-toros-botella.png",
        "descripcion": "Paso de los Toros Pomelo, en latas de 330 cc y botellas de 1.5 litros, presenta sus gaseosas con sabor a pomelo. Esta opción única ofrece una experiencia refrescante y distintiva para aquellos que buscan nuevos sabores.",
        "precio": 700,
       "stock": 19
    },
    {
        "idx": 888,
        "marca": "Villavicencio",
        "tamanio": "500 cc",
        "tipo": "Agua con gas",
        "formato": "Botella",
        "categoria": "BebidasSinAlcohol",
        "foto": "../src/assets/villavicencio-con-gas.png",
        "descripcion": "Villavicencio, en botellas de 500 cc, ofrece agua con gas para aquellos que buscan una alternativa burbujeante. Proveniente de fuentes naturales, esta opción combina frescura con un toque efervescente.",
        "precio": 250,
       "stock": 19
    },
    {
        "idx": 787,
        "marca": "Chivas",
        "tamanio": "1 litro",
        "tipo": "Whisky",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/chivas-regal.png",
        "descripcion": "Chivas, en presentaciones de 1 litro, destaca como una opción premium de whisky. Esta marca ofrece una experiencia única para los aficionados al whisky, con su distintivo sabor y calidad.",
        "precio": 7000,
       "stock": 19
    },
    {
        "idx": 121,
        "marca": "Johnnie Walker Red Label",
        "tamanio": "1 litro",
        "tipo": "Whisky",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/red-label.png",
        "descripcion": "Johnnie Walker, con sus variedades Red Label, Black Label y Blue Label en botellas de 1 litro, es reconocida por su excelencia en el mundo del whisky. Cada una de estas opciones presenta características únicas, desde el equilibrio suave del Red Label hasta la sofisticación del Blue Label.",
        "precio": 12000,
       "stock": 19
    },
    {
        "idx": 232,
        "marca": "Johnnie Walker Black Label",
        "tamanio": "1 litro",
        "tipo": "Whisky",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/black-label.png",
        "descripcion": "Johnnie Walker, con sus variedades Red Label, Black Label y Blue Label en botellas de 1 litro, es reconocida por su excelencia en el mundo del whisky. Cada una de estas opciones presenta características únicas, desde el equilibrio suave del Red Label hasta la sofisticación del Blue Label.",
        "precio": 20000,
       "stock": 19
    },
    {
        "idx": 343,
        "marca": "Johnnie Walker Blue Label",
        "tamanio": "1 litro",
        "tipo": "Whisky",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/blue-label.png",
        "descripcion": "Johnnie Walker, con sus variedades Red Label, Black Label y Blue Label en botellas de 1 litro, es reconocida por su excelencia en el mundo del whisky. Cada una de estas opciones presenta características únicas, desde el equilibrio suave del Red Label hasta la sofisticación del Blue Label.",
        "precio": 90000,
       "stock": 19
    },
    {
        "idx": 454,
        "marca": "Trumpeter Malbec",
        "tamanio": "1 litro",
        "tipo": "Vino",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/vino-trumpeter.png",
        "descripcion": "Trumpeter Malbec, en botella de 1 litro, ofrece una opcion de vino para los amantes de esta bebida. Con su origen y calidad distintivos, esta marca brinda experiencias únicas en cada sorbo.",
        "precio": 7000,
       "stock": 19
    },
    {
        "idx": 565,
        "marca": "Nicassia Malbec",
        "tamanio": "1 litro",
        "tipo": "Vino",
        "formato": "Botella",
        "categoria": "BebidasConAlcohol",
        "foto": "../src/assets/vino-nicasia.png",
        "descripcion": "Nicassia Malbec, en botella de 1 litro, ofrece una opcion de vino para los amantes de esta bebida. Con su origen y calidad distintivos, esta marca brinda experiencias únicas en cada sorbo.",
        "precio": 6500,
       "stock": 19
    },
    {
        "idx": 774,
        "marca": "Müecas",
        "tamanio": "200grs",
        "tipo": "Barritas de cereal",
        "formato": "individual",
        "categoria": "Alimento",
        "foto": "../src/assets/barritas-muecas-todos-sabores.png",
        "descripcion": "Müecas, con sus barritas de cereal en presentación de 200 gramos, se presenta como una opción práctica y deliciosa para aquellos que buscan un snack saludable. Estas barritas son ideales para satisfacer antojos entre comidas.",
        "precio": 450,
       "stock": 19
    },
    {
        "idx": 887,
        "marca": "Don Lorenzo",
        "tamanio": "1kg",
        "tipo": "Pan dulce",
        "formato": "individual",
        "categoria": "Alimento",
        "foto": "../src/assets/pan-dulce-frutas-don-lorenzo.png",
        "descripcion": "Don Lorenzo, en su presentación de 1 kg, ofrece pan dulce de calidad. Esta marca es reconocida por su calidad y sabor excepcional, siendo una elección ideal para disfrutar durante las festividades o como acompañamiento en cualquier ocasión.",
        "precio": 700,
        "stock": 19
    },
    {
        "idx": 545,
        "marca": "Valido",
        "tamanio": "1kg",
        "tipo": "Pan dulce",
        "formato": "individual",
        "categoria": "Alimento",
        "foto": "../src/assets/pan-dulce-frutas-valido.png",
        "descripcion": "Valido, en su presentación de 1 kg, ofrece pan dulce de calidad. Esta marca es reconocida por su calidad y sabor excepcional, siendo una elección ideal para disfrutar durante las festividades o como acompañamiento en cualquier ocasión.",
        "precio": 750,
        "stock": 19
    }
]

